### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by Takuto-Koyama** [dmis-lab/MulinforCPI#1]
I'd like to try this model, but I think "match_protein_index_esm.py" is missing.

**Comment by quangnguyenbn99** [comment]
Hello,

I would like to express my sincere gratitude for your attention to our work and for bringing the missing file to our notice. I'm pleased to inform you that the file has been successfully uploaded.

Thank you once again.

Best regards,

**Comment by Takuto-Koyama** [comment]
Thanks a lot!
