### ISSUE TITLE
The purpose of using "where" and "what" information?

### ISSUE THREAD

**Issue by BioBabyCode** [dmis-lab/MulinforCPI#2]
Could you please provide some insight into why you utilized the terms "where" and "what" in your paper?

**Comment by quangnguyenbn99** [comment]
Hello,
Given the inherent dependence of real-world CPI prediction tasks on complex chemical interactions, our aim is to augment the representations of atomic features, referred to as 'what', by integrating additional contextual information, referred to as 'where'. Our goal is to enhance the model's understanding of the nuanced interplay between chemical data and the structural characteristics of compounds.
