### ISSUE TITLE
About the experiment on Davis dataset

### ISSUE THREAD

**Issue by Victory1234567890** [dmis-lab/MulinforCPI#3]
Hi there!

I'm unsure about the experiment described in the paper. Specifically, I'm confused about whether the setting of the novel-pair in the Davis dataset is the same as the one used in PreciverCPI. Could you please clarify this for me?

Thank you!
![图片1](https://github.com/dmis-lab/MulinforCPI/assets/163712040/f2bc685c-6793-49d9-a8cc-440b67fc6a59)
![图片2](https://github.com/dmis-lab/MulinforCPI/assets/163712040/46d5463a-8f45-4e98-a2ce-73ed08ebd618)

**Comment by quangnguyenbn99** [comment]
Hi. Thank you for your interest in our work.
Yes, the settings have been adjusted.
In our previous study, PerceiverCPI, a conventional five-fold cross-validation methodology was utilized. However, in this current research endeavor, we have introduced a novel testing strategy known as 5-cluster cross-validation. We invite you to delve into the CROSS-CLUSTER VALIDATION section for comprehensive elucidation.
Hope it helps, and happy exploring!

**Comment by Victory1234567890** [comment]
Thank you for clearing up my confusion regarding the experiment in the paper.
Best regards,
